steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/ml-models/iris-predictor:$COMMIT_SHA', '.']

# Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/ml-models/iris-predictor:$COMMIT_SHA']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'iris-predictor'
  - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/ml-models/iris-predictor:$COMMIT_SHA'
  - '--region=us-central1'
  - '--platform=managed'
  - '--allow-unauthenticated'

# Store images in Artifact Registry
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/ml-models/iris-predictor:$COMMIT_SHA'